[build]
  command = "chmod +x ./scripts/dependency_installation.sh && ./scripts/dependency_installation.sh && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

